  # https://asdf-vm.com/guide/getting-started.html#official-download
- name: ASDF | install from git
  ansible.builtin.git:
    repo: 'https://github.com/asdf-vm/asdf.git'
    dest: $HOME/.asdf
    version: v0.11.2

- name: ASDF | Setup in bashrc
  ansible.builtin.lineinfile:
    path: .bashrc
    line: "source \"$HOME/.asdf/asdf.sh\""

- name: ASDF | test
  ansible.builtin.shell: "asdf"
  changed_when: false

- name: Crate $HOME/.tool-versions with ansible
  ansible.builtin.lineinfile:
    create: true
    path: .tool-versions
    line: "ansible-base 2.10.17"

- name: ASDF | add plugin ansible-base
  changed_when: false
  ansible.builtin.shell: "asdf plugin add ansible-base || true"

- name: ASDF | install ansible-base
  changed_when: false
  ansible.builtin.shell: "asdf install ansible-base || true"

- name: ASDF | test ansible
  ansible.builtin.shell: "source $HOME/.bashrc && ansible --version | head -n1"
  register: ansible

- name: Show ansible
  debug:
    msg: "{{ ansible.stdout_lines }}"
