---
- name: Install ansible to the controller VM
  hosts: controller
  roles:
    - role: ansible-asdf
      tags: ansible-asdf

- name: Prepare vagrant environment
  hosts: all
  roles:
    - role: vagrant-env-prep
      tags: vagrant

- name: Prepare RKE2 tarball deployment
  hosts: all
  roles:
    - role: rke2-tarball-prep
      tags: rke2

