# brind down/up ifaces and discard any errors
- name: ifdownup
  shell: |
    ifdown eth1 || true &&
    ifup eth1 || true &&
    ifdown eth0 || true &&
    ifup eth0 || true
  changed_when: false
  become: true
