# brind down/up ifaces and discard any errors
- name: restart network ifupdown
  shell: |
    ifdown eth1 || true &&
    ifup eth1 || true &&
    ifdown eth0 || true &&
    ifup eth0 || true
  changed_when: false
  become: true
  when: ansible_distribution == "CentOS"

- name: restart network nmcli
  shell: nmcli networking off; nmcli networking on;
  changed_when: false
  become: true
  when: ( ansible_distribution == 'Rocky' ) or ( ansible_distribution == 'RedHat')
