- name: Import prep tasks
  ansible.builtin.import_tasks: prep.yml
  delegate_to: localhost
  run_once: true

- name: Upload rke2 repo with tarballs and inventory to the controller
  ansible.posix.synchronize:
    src: "{{ rke2_ansible_repo_tmp }}"
    dest: ./
    owner: true
    group: true
  when: inventory_hostname == 'controller'
  tags: my-cluster
  run_once: true

- name: Verify controller can do ansible ping to all VMs
  ansible.builtin.shell:
    chdir: ~/rke2-ansible
    cmd: ansible all -m ping
  when: inventory_hostname == 'controller'
  tags: ['my-cluster','ping']
  run_once: true
  register: ping
  failed_when: ping.stderr or ping.rc !=0
