---
- name: Set var for eth1 gateway
  set_fact:
    eth1_gw4_addr: "{{ vagrant_ip.split('.')[0] }}.{{ vagrant_ip.split('.')[1] }}.{{ vagrant_ip.split('.')[2] }}.1"

# -- airgap on
- block:
  - name: Airgap on | Disable default route for eth0
    community.general.nmcli:
      type: ethernet
      conn_name: System eth0
      never_default4: true
      state: present

  - name: Airgap on | Enable default route for eth1
    community.general.nmcli:
      type: ethernet
      conn_name: eth1
      gw4: "{{ eth1_gw4_addr }}"
      state: present
    notify: 
      - ifdownup
      - ifdownup Rocky

  - meta: flush_handlers

  - name: Airgap on | Test no internet access
    shell: "ping -W1 -c1 {{ internet_ip_test_addr }}"
    register: first_ping
    until: first_ping.rc != 0
    retries: 3
    delay: 1
    failed_when: false
    changed_when: first_ping.rc == 0
    notify:
      - ifdownup
      - ifdownup Rocky

  - meta: flush_handlers

  - name: Airgap on | Final test no internet access
    shell: "ping -W1 -c1 {{ internet_ip_test_addr }}"
    when: first_ping.changed
    register: second_ping
    until: second_ping.rc != 0
    retries: 3
    delay: 1
    failed_when: second_ping.rc == 0
    changed_when: false

  - name: Airgap on | Confirm eth1 gateway ping
    shell: "ping -W1 -c1 {{ eth1_gw4_addr }}"
    register: first_gateway_ping
    failed_when: false
    until: first_gateway_ping.rc == 0
    changed_when: first_gateway_ping.rc != 0
    retries: 3
    delay: 1
    notify: 
      - ifdownup
      - ifdownup Rocky

  - meta: flush_handlers

  - name: Airgap on | Final eth1 gateway ping
    shell: "ping -W1 -c1 {{ eth1_gw4_addr }}"
    register: second_gateway_ping


  when: airgap | bool

# -- airgap off
- block:
  - name: Airgap off | Enable default route for eth0
    community.general.nmcli:
      type: ethernet
      conn_name: System eth0
      ifname: eth0
      never_default4: false
      state: present

  - name: Airgap off | Disable default route for eth1
    community.general.nmcli:
      type: ethernet
      conn_name: eth1
      never_default4: true
      state: present
    notify: 
      - ifdownup
      - ifdownup Rocky

  - meta: flush_handlers

  - name: Airgap off | Test for internet access
    shell: "ping -W1 -c1 {{ internet_ip_test_addr }}"
    register: first_ping
    until: first_ping.rc == 0
    retries: 3
    delay: 1
    failed_when:  false
    changed_when: first_ping.rc != 0
    notify: 
      - ifdownup
      - ifdownup Rocky

  - meta: flush_handlers

  - name: Airgap off | Final test of internet access
    shell: "ping -W1 -c1 {{ internet_ip_test_addr }}"
    when: first_ping.changed
    register: second_ping
    until: second_ping.rc == 0
    retries: 3
    delay: 1
    failed_when:  second_ping.rc != 0
    changed_when: false

  when: not airgap | bool
