---
- name: YUM | Install epel-release onto controller
  become: true
  ansible.builtin.yum:
    update_cache: true
    state: latest
    name:
     - epel-release

- name: YUM | Install python 3 onto controller
  become: true
  ansible.builtin.yum:
    update_cache: true
    state: latest
    name: python3
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int > 7

  # https://unix.stackexchange.com/questions/433046/how-do-i-enable-centos-repositories-on-rhel-red-hat
- name: YUM | RHEL7 add CentOS7 repo
  become: true
  ansible.builtin.yum_repository:
    name: centos
    description: work around ansible installation issues
    baseurl: http://ftp.heanet.ie/pub/centos/7/os/x86_64/
    gpgcheck: true
    gpgkey: http://ftp.heanet.ie/pub/centos/7/os/x86_64/RPM-GPG-KEY-CentOS-7
  when:
    - ansible_distribution == 'RedHat'
    - ansible_distribution_major_version|int == 7

- name: YUM | Install ansible RHEL7
  become: true
  ansible.builtin.yum:
    update_cache: true
    state: latest
    name: ansible
  when:
    - (ansible_distribution == 'CentOS') or (ansible_distribution == 'RedHat')
    - ansible_distribution_major_version|int == 7

- name: YUM | Install ansible Rocky
  become: true
  ansible.builtin.yum:
    update_cache: true
    state: latest
    name: ansible
  when:
    - ansible_distribution == "Rocky"


# - PIP3

- name: PIP3 | Install ansible
  become: false
  ansible.builtin.pip:
    name: ansible
    executable: pip3
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != "Rocky"
    - ansible_distribution_major_version|int > 7

- name: Upgrade pip3 to latest
  become: true
  ansible.builtin.shell: "pip3 install --upgrade pip"
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int > 7

# -------

- name: Get ansible version
  ansible.builtin.shell: "ansible --version"
  register: ansible

- name: Show ansible version
  debug:
    msg: "{{ ansible.stdout_lines }}"