---
- name: Generate ssh key for controller node
  community.crypto.openssh_keypair:
    path: ~/.ssh/id_rsa
    size: 2048
    comment: "vagrant@controller"
  when: inventory_hostname == 'controller'
  tags: ssh
  register: sshkey

- name: Add controller's ssh pub to rke nodes
  ansible.posix.authorized_key:
    user: vagrant
    state: present
    key: "{{ hostvars['controller']['sshkey']['public_key'] }} {{ hostvars['controller']['sshkey']['comment'] }}"
  when: inventory_hostname != 'controller'
  tags: ssh

- name: Read IP address from Vagrantfile
  set_fact:
    vagrant_ip: "{{ lookup('file', '{{ playbook_dir}}/Vagrantfile') | regex_search(inventory_hostname + '.+') | regex_search('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b')}}"
  tags: ['airgap','etchosts']

- name: Setup /etc/hosts names
  become: true
  ansible.builtin.template:
    backup: true
    src: etc-hosts.j2
    dest: /etc/hosts
  tags: etchosts

- name: Add kubectl alias to master
  ansible.builtin.lineinfile:
    path: "$HOME/.bashrc"
    line: "alias kubectl='sudo /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml'"
    state: present
    insertafter: EOF
  tags: aliases
  when: vm_role == 'server'
