---
- name: Install epel-release onto controller
  become: true
  ansible.builtin.dnf:
    update_cache: true
    state: latest
    name:
     - epel-release
  when: inventory_hostname == 'controller'
  tags: packages

- name: Install required apps onto controller
  become: true
  ansible.builtin.dnf:
    update_cache: true
    state: present
    name: "{{ packages.controller }}"
  when: inventory_hostname == 'controller'
  tags: packages
