---
- name: Execute common tasks
  ansible.builtin.import_tasks: common.yml

- name: RHEL | configure networking
  ansible.builtin.import_tasks: network-nmcli.yml
  when: ansible_os_family == "RedHat"
  tags: network
  become: true


- name: RHEL | apply airgap settings
  ansible.builtin.import_tasks: airgap-nmcli.yml
  when: ansible_os_family == "RedHat"
  tags: airgap
  become: true

- name: RHEL | disable all repos (airgap causes install timeouts)
  ansible.builtin.shell: "yum-config-manager --disable \\*"
  when: ansible_os_family == "RedHat"
  tags: disable-repos
  become: true
