---
- name: Execute common tasks
  import_tasks: common.yml

- name: Execute yum installs
  import_tasks: yum.yml
  when: ansible_pkg_mgr == "yum"

- name: Apply RHEL airgap settings
  import_tasks: airgap-nmcli.yml
  when: ansible_os_family == "RedHat"
  tags: airgap
  become: true