---
- name: Execute common tasks
  ansible.builtin.import_tasks: common.yml

- name: RHEL | configure networking
  ansible.builtin.import_tasks: network-nmcli.yml
  when: ansible_os_family == "RedHat"
  tags: network
  become: true

- name: YUM | execute package installs
  ansible.builtin.import_tasks: yum.yml
  when: ansible_pkg_mgr == "yum"

- name: RHEL | apply airgap settings
  ansible.builtin.import_tasks: airgap-nmcli.yml
  when: ansible_os_family == "RedHat"
  tags: airgap
  become: true