---
- name: NMCLI | Configure eth1
  community.general.nmcli:
    type: ethernet
    ifname: eth1
    conn_name: eth1
    ip4: "{{ vagrant_ip }}/24"
    never_default4: true
    state: present
  notify:
    - restart network ifupdown
    - restart network nmcli